<a href="https://colab.research.google.com/github/varuntej1310/camscanner/blob/master/divider_script.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
subtractor = open("subtractor.v","w")
subtractor.write("module subtractor(x,y,bin,qs,r,bout); \n \n")
subtractor.write("input x,y,bin,qs; \n")
subtractor.write("output r,bout; \n")
subtractor.write("wire diff; \n")
subtractor.write("assign diff = x^y^bin; \n")
subtractor.write("assign bout = (~x & y)|((~(x^y)) & bin); \n")
subtractor.write("assign r = qs?diff:x; \n")
subtractor.write("endmodule\n")
subtractor.close()

approx_exist = input("Is approximate subtractor present?(y/n)")
if approx_exist == "y":
  diff = input("enter the difference equation in terms of x,y,bin:")
  bout = input("enter the borrow equation in terms of x,y,bin:")

  subtractor_old = open("subtractor.v","r")
  subtractor_new = open("subtractor_approx.v","w")

  Lines = subtractor_old.readlines() 

  for line in Lines:
    if line.strip() == "assign diff = x^y^bin;" :
      subtractor_new.write("assign diff = "+diff+";"+"\n" )
    elif line.strip() == "assign bout = (~x & y)|((~(x^y)) & bin);" :
      subtractor_new.write("assign bout = "+bout+";"+"\n" )
    elif line.strip() == "module subtractor(x,y,bin,qs,r,bout);" :
      subtractor_new.write("module subtractor_approx(x,y,bin,qs,r,bout);"+"\n" )
    else:
      subtractor_new.write(line.strip() + "\n")

  subtractor_old.close()
  subtractor_new.close()



Is approximate subtractor present?(y/n)n


In [ ]:
import numpy as np
n = int(input("enter the value of N for 2N/N divider:"))
entries = list(map(int, input("Enter a NxN matrix with 0-> exact and 1-> approximate").split())) 
matrix = np.array(entries).reshape(n, n) 
print(matrix)


divider = open("divider_script.v","w")

divider.write("module divider_script(n,d,q,r);"+"\n")
divider.write("input ["+str(2*(n)-1)+":0]n;"+"\n")
divider.write("input ["+str(n-1)+":0]d;"+"\n")
divider.write("input ["+str(n-1)+":0]q,r;"+"\n \n")

divider.write("wire ["+str(n-1)+":0]bout_local[0:"+str(n-1)+"];"+"\n")
divider.write("wire ["+str(n-1)+":0]r_local[0:"+str(n-1)+"];"+"\n \n")
x=0
for i in range(n):
  if matrix[n-1-i][n-1] == 1:
    divider.write("subtractor_approx sb"+str(x)+"(n["+str(i)+"],d[0],0,q["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
  else:
    divider.write("subtractor sb"+str(x)+"(n["+str(i)+"],d[0],0,q["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
  i=i+1
  x=x+1

i=0
for i in range(n-1):
  if matrix[0][n-2-i] == 1:
    divider.write("subtractor_approx sb"+str(x)+"(n["+str(x)+"],d["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
  else:
    divider.write("subtractor sb"+str(x)+"(n["+str(x)+"],d["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
  i=i+1
  x=x+1

i=0
for i in range(n-1):
  for j in range(n-1):
    if matrix[n-i-1][n-2-j] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
    j=j+1
    x=x+1
  i=i+1

i=0
for i in range(n-1):
  divider.write("assign q["+str(i)+"] = (r_local["+str(i+1)+"]["+str(n-1)+"])|(~bout_local["+str(i)+"]["+str(n-1)+"]); \n")

divider.write("assign q["+str(n-1)+"] = (n["+str((2*n-1))+"])|(~bout_local["+str(n-1)+"]["+str(n-1)+"]); \n")

i =0
for i in range(n):
  divider.write("assign r["+str(i)+"] = r_local[0]["+str(i)+"]; \n")

divider.write("endmodule \n")
divider.close()





enter the value of N for 2N/N divider:8
Enter a NxN matrix with 0-> exact and 1-> approximate0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
import numpy as np
n=int(input())
x=n-1
y=n
for i in range(n):
  m=[]
  for j in range (n*x):
    m.append(0)
  for l in range(n*(n-x)):
    m.append(1)
  x=x-1
  matrix = np.array(m).reshape(n,n)
  matrix_transpose = matrix.transpose()
  print(matrix_transpose)
  print(matrix)
  print("\n \n")



In [ ]:
import numpy as np
n=4
x=n
for i in range(n):
  a=[]
  for j in range(n*(x-1)):
    a.append(0)
  for k in range(i+1):
    for h in range(n-k-1):
      a.append(0)
    for l in range(k+1):
      a.append(1)  

  x=x-1
  matrix = np.array(a).reshape(n,n)
  print(matrix)
  print("\n \n")



In [ ]:
import numpy as np

########################    Exact Subtractor   ################################

subtractor = open("subtractor.v","w")
subtractor.write("module subtractor(x_exact,y_exact,bin_exact,qs_exact,r_sub_exact,bout_exact); \n \n")
subtractor.write("input x_exact,y_exact,bin_exact,qs_exact; \n")
subtractor.write("output r_sub_exact,bout_exact; \n")
subtractor.write("wire diff_exact; \n")
subtractor.write("assign diff_exact = x_exact^y_exact^bin_exact; \n")
subtractor.write("assign bout_exact = (~x_exact & y_exact)|((~(x_exact^y_exact)) & bin_exact); \n")
subtractor.write("assign r_sub_exact = qs_exact?diff_exact:x_exact; \n")
subtractor.write("endmodule\n")
subtractor.close()

########################    Approximate Subtractor   ################################

#approx_exist = input("Is approximate subtractor present?(y/n)")
#if approx_exist == "y":
diff = input("enter the difference equation in terms of x,y,bin:")
bout = input("enter the borrow equation in terms of x,y,bin:")
subtractor_new = open("subtractor_approx.v","w")
subtractor_new.write("module subtractor_approx(x,y,bin,qs,r_sub,bout); \n \n")
subtractor_new.write("input x,y,bin,qs; \n")
subtractor_new.write("output r_sub,bout; \n")
subtractor_new.write("wire diff; \n")
subtractor_new.write("assign diff = "+diff+";"+"\n")
subtractor_new.write("assign bout = "+bout+";"+"\n")
subtractor_new.write("assign r_sub = qs?diff:x; \n")
subtractor_new.write("endmodule\n")
subtractor_new.close()
  

#######################   Row Approximation    ##########################################

n = int(input("enter the value of N for 2N/N divider:"))
x_iter=n-1
for i_iter in range(n):
  m=[]
  for j_iter in range (n*x_iter):
    m.append(0)
  for l_iter in range(n*(n-x_iter)):
    m.append(1)
  x_iter=x_iter-1
  matrix = np.array(m).reshape(n,n)
  #print(matrix)

  divider = open("divider_array_row_"+str(i_iter+1)+".v","w")
  #print(divider)
  divider.write("module divider_array_row_"+str(i_iter+1)+"(n,d,q,r,clk);"+"\n")
  divider.write("input ["+str(2*(n)-1)+":0]n;"+"\n")
  divider.write("input ["+str(n-1)+":0]d;"+"\n" + "input clk;"+"\n")
  divider.write("output ["+str(n-1)+":0]q,r;"+"\n \n")

  divider.write("reg ["+str(2*(n)-1)+":0]n1;"+"\n")
  divider.write("reg ["+str(n-1)+":0]d1;"+"\n")
  divider.write("wire ["+str(n-1)+":0]q1,r1;"+"\n")
  divider.write("reg ["+str(n-1)+":0]q,r;"+"\n")
  divider.write("wire ["+str(n-1)+":0]bout_local[0:"+str(n-1)+"];"+"\n")
  divider.write("wire ["+str(n-1)+":0]r_local[0:"+str(n-1)+"];"+"\n \n")

  divider.write("always@(posedge clk)"+"\n"+"begin"+"\n"+"n1 <= n;"+"\n"+"d1 <= d;"+"\n"+"q <= q1;"+"\n"+"r <= r1;"+"\n"+"end"+"\n")

  x=0
  for i in range(n):
    if matrix[n-1-i][n-1] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(n1["+str(i)+"],d1[0],1'b0,q1["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(n1["+str(i)+"],d1[0],1'b0,q1["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
    i=i+1
    x=x+1

  i=0
  for i in range(n-1):
    if matrix[0][n-2-i] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(n1["+str(x)+"],d1["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q1["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(n1["+str(x)+"],d1["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q1["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
    i=i+1
    x=x+1

  i=0
  for i in range(n-1):
    for j in range(n-1):
      if matrix[n-i-1][n-2-j] == 1:
        divider.write("subtractor_approx sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d1["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q1["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
      else:
        divider.write("subtractor sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d1["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q1["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
      j=j+1
      x=x+1
    i=i+1

  i=0
  for i in range(n-1):
    divider.write("assign q1["+str(i)+"] = (r_local["+str(i+1)+"]["+str(n-1)+"])|(~bout_local["+str(i)+"]["+str(n-1)+"]); \n")

  divider.write("assign q1["+str(n-1)+"] = (n1["+str((2*n-1))+"])|(~bout_local["+str(n-1)+"]["+str(n-1)+"]); \n")

  i =0
  for i in range(n):
    divider.write("assign r1["+str(i)+"] = r_local[0]["+str(i)+"]; \n")

  divider.write("endmodule \n")
  divider.close()

#######################   Column Approximation    ##########################################

i_iter=j_iter=0
i=j=0
x_iter=n-1
for i_iter in range(n):
  m=[]
  for j_iter in range (n*x_iter):
    m.append(0)
  for l_iter in range(n*(n-x_iter)):
    m.append(1)
  x_iter=x_iter-1
  matrix_original = np.array(m).reshape(n,n)
  matrix = matrix_original.transpose()
  #print(matrix)

  divider = open("divider_array_column_"+str(i_iter+1)+".v","w")
  #print(divider)
  divider.write("module divider_array_column_"+str(i_iter+1)+"(n,d,q,r,clk);"+"\n")
  divider.write("input ["+str(2*(n)-1)+":0]n;"+"\n")
  divider.write("input ["+str(n-1)+":0]d;"+"\n" + "input clk;"+"\n")
  divider.write("output ["+str(n-1)+":0]q,r;"+"\n \n")

  divider.write("reg ["+str(2*(n)-1)+":0]n1;"+"\n")
  divider.write("reg ["+str(n-1)+":0]d1;"+"\n")
  divider.write("wire ["+str(n-1)+":0]q1,r1;"+"\n")
  divider.write("reg ["+str(n-1)+":0]q,r;"+"\n")
  divider.write("wire ["+str(n-1)+":0]bout_local[0:"+str(n-1)+"];"+"\n")
  divider.write("wire ["+str(n-1)+":0]r_local[0:"+str(n-1)+"];"+"\n \n")

  divider.write("always@(posedge clk)"+"\n"+"begin"+"\n"+"n1 <= n;"+"\n"+"d1 <= d;"+"\n"+"q <= q1;"+"\n"+"r <= r1;"+"\n"+"end"+"\n")
  
  x=0
  for i in range(n):
    if matrix[n-1-i][n-1] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(n1["+str(i)+"],d1[0],1'b0,q1["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(n1["+str(i)+"],d1[0],1'b0,q1["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
    i=i+1
    x=x+1

  i=0
  for i in range(n-1):
    if matrix[0][n-2-i] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(n1["+str(x)+"],d1["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q1["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(n1["+str(x)+"],d1["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q1["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
    i=i+1
    x=x+1

  i=0
  for i in range(n-1):
    for j in range(n-1):
      if matrix[n-i-1][n-2-j] == 1:
        divider.write("subtractor_approx sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d1["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q1["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
      else:
        divider.write("subtractor sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d1["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q1["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
      j=j+1
      x=x+1
    i=i+1

  i=0
  for i in range(n-1):
    divider.write("assign q1["+str(i)+"] = (r_local["+str(i+1)+"]["+str(n-1)+"])|(~bout_local["+str(i)+"]["+str(n-1)+"]); \n")

  divider.write("assign q1["+str(n-1)+"] = (n1["+str((2*n-1))+"])|(~bout_local["+str(n-1)+"]["+str(n-1)+"]); \n")

  i =0
  for i in range(n):
    divider.write("assign r1["+str(i)+"] = r_local[0]["+str(i)+"]; \n")

  divider.write("endmodule \n")
  divider.close()

#######################   Triangular Approximation    ##########################################

i_iter=j_iter=0
i=j=0
x_iter=n
for i_iter in range(n):
  m=[]
  for j_iter in range (n*(x_iter-1)):
    m.append(0)
  for k_iter in range(i_iter+1):
    for h_iter in range(n-k_iter-1):
      m.append(0)
    for l_iter in range(k_iter+1):
      m.append(1)
  x_iter = x_iter-1
  matrix = np.array(m).reshape(n,n)
  #print(matrix)

  divider = open("divider_array_traingular_"+str(i_iter+1)+".v","w")
  #print(divider)
  divider.write("module divider_array_traingular_"+str(i_iter+1)+"(n,d,q,r,clk);"+"\n")
  divider.write("input ["+str(2*(n)-1)+":0]n;"+"\n")
  divider.write("input ["+str(n-1)+":0]d;"+"\n" + "input clk;"+"\n")
  divider.write("output ["+str(n-1)+":0]q,r;"+"\n \n")

  divider.write("reg ["+str(2*(n)-1)+":0]n1;"+"\n")
  divider.write("reg ["+str(n-1)+":0]d1;"+"\n")
  divider.write("wire ["+str(n-1)+":0]q1,r1;"+"\n")  
  divider.write("reg ["+str(n-1)+":0]q,r;"+"\n")
  divider.write("wire ["+str(n-1)+":0]bout_local[0:"+str(n-1)+"];"+"\n")
  divider.write("wire ["+str(n-1)+":0]r_local[0:"+str(n-1)+"];"+"\n \n")

  divider.write("always@(posedge clk)"+"\n"+"begin"+"\n"+"n1 <= n;"+"\n"+"d1 <= d;"+"\n"+"q <= q1;"+"\n"+"r <= r1;"+"\n"+"end"+"\n")
  
  x=0
  for i in range(n):
    if matrix[n-1-i][n-1] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(n1["+str(i)+"],d1[0],1'b0,q1["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(n1["+str(i)+"],d1[0],1'b0,q1["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
    i=i+1
    x=x+1

  i=0
  for i in range(n-1):
    if matrix[0][n-2-i] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(n1["+str(x)+"],d1["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q1["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(n1["+str(x)+"],d1["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q1["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
    i=i+1
    x=x+1

  i=0
  for i in range(n-1):
    for j in range(n-1):
      if matrix[n-i-1][n-2-j] == 1:
        divider.write("subtractor_approx sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d1["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q1["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
      else:
        divider.write("subtractor sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d1["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q1["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
      j=j+1
      x=x+1
    i=i+1

  i=0
  for i in range(n-1):
    divider.write("assign q1["+str(i)+"] = (r_local["+str(i+1)+"]["+str(n-1)+"])|(~bout_local["+str(i)+"]["+str(n-1)+"]); \n")

  divider.write("assign q1["+str(n-1)+"] = (n1["+str((2*n-1))+"])|(~bout_local["+str(n-1)+"]["+str(n-1)+"]); \n")

  i =0
  for i in range(n):
    divider.write("assign r1["+str(i)+"] = r_local[0]["+str(i)+"]; \n")

  divider.write("endmodule \n")
  divider.close()



enter the difference equation in terms of x,y,bin:x^y^bin
enter the borrow equation in terms of x,y,bin:(~x & y)|((~(x^y)) & bin)
enter the value of N for 2N/N divider:8


In [ ]:
import numpy as np
n = int(input("enter the value of N for 2N/N divider:"))
x_iter=n-1
for i_iter in range(n):
  m=[]
  for j_iter in range (n*x_iter):
    m.append(0)
  for l_iter in range(n*(n-x_iter)):
    m.append(1)
  x_iter=x_iter-1
  matrix_original = np.array(m).reshape(n,n)
  matrix = matrix_original.transpose()
  #print(matrix)

  divider = open("divider_array_column_"+str(i_iter+1)+".v","w")
  #print(divider)
  divider.write("module divider_array_row_"+str(i_iter)+"(n,d,q,r);"+"\n")
  divider.write("input ["+str(2*(n)-1)+":0]n;"+"\n")
  divider.write("input ["+str(n-1)+":0]d;"+"\n")
  divider.write("input ["+str(n-1)+":0]q,r;"+"\n \n")

  divider.write("wire ["+str(n-1)+":0]bout_local[0:"+str(n-1)+"];"+"\n")
  divider.write("wire ["+str(n-1)+":0]r_local[0:"+str(n-1)+"];"+"\n \n")
  x=0
  for i in range(n):
    if matrix[n-1-i][n-1] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(n["+str(i)+"],d[0],0,q["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(n["+str(i)+"],d[0],0,q["+str(i)+"],r_local["+str(i)+"][0],bout_local["+str(i)+"][0]);"+"\n");
    i=i+1
    x=x+1

  i=0
  for i in range(n-1):
    if matrix[0][n-2-i] == 1:
      divider.write("subtractor_approx sb"+str(x)+"(n["+str(x)+"],d["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
    else:
      divider.write("subtractor sb"+str(x)+"(n["+str(x)+"],d["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i)+"]"+",q["+str(n-1)+"],r_local["+str(n-1)+"]["+str(i+1)+"],bout_local["+str(n-1)+"]["+str(i+1)+"]);"+"\n");
    i=i+1
    x=x+1

  i=0
  for i in range(n-1):
    for j in range(n-1):
      if matrix[n-i-1][n-2-j] == 1:
        divider.write("subtractor_approx sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
      else:
        divider.write("subtractor sb"+str(x)+"(r_local["+str(i+1)+"]["+str(j)+"],d["+str(j+1)+"],bout_local["+str(i)+"]["+str(j)+"]"+",q["+str(i)+"],r_local["+str(i)+"]["+str(j+1)+"],bout_local["+str(i)+"]["+str(j+1)+"]);"+"\n");
      j=j+1
      x=x+1
    i=i+1

  i=0
  for i in range(n-1):
    divider.write("assign q["+str(i)+"] = (r_local["+str(i+1)+"]["+str(n-1)+"])|(~bout_local["+str(i)+"]["+str(n-1)+"]); \n")

  divider.write("assign q["+str(n-1)+"] = (n["+str((2*n-1))+"])|(~bout_local["+str(n-1)+"]["+str(n-1)+"]); \n")

  i =0
  for i in range(n):
    divider.write("assign r["+str(i)+"] = r_local[0]["+str(i)+"]; \n")

  divider.write("endmodule \n")
  divider.close()





enter the value of N for 2N/N divider:8


In [ ]:
import os

cwd = os.getcwd()

for i in range (12):
  new=os.mkdir("\design"+str(i+1))
  


In [ ]:
test=open("test.txt","w")
test_f()
test.close()

In [ ]:
def test_f():
  for i in range(20):
    test.write(str(i)+"\n")
  return